config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  get 'pages/about'

  resources :dogs
  resources :vets
  resources :owners

  root 'admin/pages#index'

end

app/models/breed.rb
class Breed < ActiveRecord::Base
  has_many :dogs

  validates :name, presence: true


  scope :recent, -> (minutes_past=60){where("created_at >?",minutes_past.minutes.ago)}
  scope :today, -> {where('DATE(created_at)=?',Date.today)}
end

app/models/custody.rb
class Custody < ActiveRecord::Base
  belongs_to :dog
  belongs_to :owner

  validates :dog_id, presence: true
  validates :owner_id, presence: true

  scope :recent, -> (minutes_past=60){where("created_at >?",minutes_past.minutes.ago)}
  scope :today, -> {where('DATE(created_at)=?',Date.today)}
end

app/models/dog.rb
class Dog < ActiveRecord::Base
  belongs_to :breed
  belongs_to :vet
  has_many :custodies
  has_many :owners, through: :custodies
  accepts_nested_attributes_for :custodies

  validates :name, presence: true
  validates :breed_id, presence: true
  validates :dob, presence: true
  validates :vet_id, presence: true
  validates :medical_info, presence: true
  validates :in_daycare, presence: true





  scope :recent, -> (minutes_past=60){where("created_at >?",minutes_past.minutes.ago)}
  scope :today, -> {where('DATE(created_at)=?',Date.today)}


  def last_name
    if custodies.empty?
      "(none)"
    else 
      custodies.first.owner.last_name
    end
  end


end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :custodies
  has_many :dogs, through: :custodies

  validates :first_name, presence: true 
  validates :last_name, presence: true 
  validates :primary_phone, presence: true 
  validates :secondary_phone, presence: true 
  validates :address, presence: true 
  validates :city, presence: true 
  validates :state, presence: true 
  validates :zip, presence: true 
  validates :emerg_name, presence: true 
  validates :emerg_phone, presence: true 

  def name
    "#{last_name}, #{first_name}"
  end
  

  scope :recent, -> (minutes_past=60){where("created_at >?",minutes_past.minutes.ago)}
  scope :today, -> {where('DATE(created_at)=?',Date.today)}
end

app/models/vet.rb
class Vet < ActiveRecord::Base
  has_many :dogs

  validates :name, presence: true
  validates :clinic, presence: true 
  validates :phone, presence: true

  scope :recent, -> (minutes_past=60){where("created_at >?",minutes_past.minutes.ago)}
  scope :today, -> {where('DATE(created_at)=?',Date.today)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
    @dog.custodies.build
  end

  # GET /dogs/1/edit
  def edit
    @dog.custodies.build
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :breed_id, :dob, :vet_id, :medical_info, :in_daycare, custodies_attributes: [:id, :owner_id, :_destroy])
    end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:first_name, :last_name, :primary_phone, :secondary_phone, :address, :city, :state, :zip, :emerg_name, :emerg_phone)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
   
  end

  def about
  end
end

app/controllers/vets_controller.rb
class VetsController < ApplicationController
  before_action :set_vet, only: [:show, :edit, :update, :destroy]

  # GET /vets
  # GET /vets.json
  def index
    @vets = Vet.all
  end

  # GET /vets/1
  # GET /vets/1.json
  def show
  end

  # GET /vets/new
  def new
    @vet = Vet.new
  end

  # GET /vets/1/edit
  def edit
  end

  # POST /vets
  # POST /vets.json
  def create
    @vet = Vet.new(vet_params)

    respond_to do |format|
      if @vet.save
        format.html { redirect_to @vet, notice: 'Vet was successfully created.' }
        format.json { render :show, status: :created, location: @vet }
      else
        format.html { render :new }
        format.json { render json: @vet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vets/1
  # PATCH/PUT /vets/1.json
  def update
    respond_to do |format|
      if @vet.update(vet_params)
        format.html { redirect_to @vet, notice: 'Vet was successfully updated.' }
        format.json { render :show, status: :ok, location: @vet }
      else
        format.html { render :edit }
        format.json { render json: @vet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vets/1
  # DELETE /vets/1.json
  def destroy
    @vet.destroy
    respond_to do |format|
      format.html { redirect_to vets_url, notice: 'Vet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vet
      @vet = Vet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vet_params
      params.require(:vet).permit(:name, :clinic, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/vets_helper.rb
module VetsHelper
end

app/views/dogs/_form.html.erb
<%= simple_form_for(@dog) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :breed %>
    <%= f.input :dob %>
    <%= f.association :vet %>
    <%= f.input :medical_info %>
    <%= f.input :in_daycare %>
    <%= f.simple_fields_for(:custodies) do |custody_fields| %>
    <%= custody_fields.association :owner, collection: Owner.order(:last_name, :first_name) %>
    <%# Only show the destroy checkbox if the record is already saved  %>
    <% if custody_fields.object.persisted? %>
    <%= custody_fileds.input :_destroy, as: :boolean %>

    <% end %>
  <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing Dog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dogs</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Breed</th>
      <th>Dob</th>
      <th>Vet</th>
      <th>Medical info</th>
      <th>In daycare</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <td><%= dog.name %></td>
        <td><%= dog.breed %></td>
        <td><%= dog.dob %></td>
        <td><%= dog.vet %></td>
        <td><%= dog.medical_info %></td>
        <td><%= dog.in_daycare %></td>
        <td><%= link_to 'Show', dog %></td>
        <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
        <td><%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dog', new_dog_path %>

app/views/dogs/new.html.erb
<h1>New Dog</h1>

<%= render 'form' %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dog.name %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @dog.breed %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @dog.dob %>
</p>

<p>
  <strong>Vet:</strong>
  <%= @dog.vet %>
</p>

<p>
  <strong>Medical info:</strong>
  <%= @dog.medical_info %>
</p>

<p>
  <strong>In daycare:</strong>
  <%= @dog.in_daycare %>
</p>

<p>
  <strong> Owners:</strong>
  <ul>
    <% @dog.owners.each do |owner| %>
    <li> <%= owner.try(:name) %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dogs_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-faded">
  <a class="navbar-brand" href="#">Navbar</a>
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Features</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Pricing</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">About</a>
    </li>
  </ul>
  <form class="form-inline pull-xs-right">
    <input class="form-control" type="text" placeholder="Search">
    <button class="btn btn-outline-success" type="submit">Search</button>
  </form>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DoggyDaycare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render '/layouts/navbar' %>

<%= yield %>

</body>
</html>

app/views/owners/_form.html.erb
<%= simple_form_for(@owner) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :primary_phone %>
    <%= f.input :secondary_phone %>
    <%= f.input :address %>
    <%= f.input :city %>
    <%= f.input :state %>
    <%= f.input :zip %>
    <%= f.input :emerg_name %>
    <%= f.input :emerg_phone %>
   
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing Owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Owners</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Primary phone</th>
      <th>Secondary phone</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Emerg name</th>
      <th>Emerg phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.first_name %></td>
        <td><%= owner.last_name %></td>
        <td><%= owner.primary_phone %></td>
        <td><%= owner.secondary_phone %></td>
        <td><%= owner.address %></td>
        <td><%= owner.city %></td>
        <td><%= owner.state %></td>
        <td><%= owner.zip %></td>
        <td><%= owner.emerg_name %></td>
        <td><%= owner.emerg_phone %></td>
        <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Owner', new_owner_path %>

app/views/owners/new.html.erb
<h1>New Owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @owner.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @owner.last_name %>
</p>

<p>
  <strong>Primary phone:</strong>
  <%= @owner.primary_phone %>
</p>

<p>
  <strong>Secondary phone:</strong>
  <%= @owner.secondary_phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @owner.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @owner.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @owner.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @owner.zip %>
</p>

<p>
  <strong>Emerg name:</strong>
  <%= @owner.emerg_name %>
</p>

<p>
  <strong>Emerg phone:</strong>
  <%= @owner.emerg_phone %>
</p>

<p>
  <strong> Owners Dog::</strong>
  <%= @owner.dog %>
</p>

<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>

app/views/pages/about.html.erb
<h1 style="text-align:center">About Doggy Daycare</h1>

<p style="text-align:center">We are located at</p> 
<p style="text-align:center">2917 Magazine Street</p> 
<p style="text-align:center">New Orleans, LA 70115</p>
<br>
<br>

<p>We are located in the Magazine </p>
<p>Commons Shopping Center,</p> 
<p>right next to C.C.'s Coffee.</p>
<br>
<p>HOURS OF OPERATION:</p>
<p>Mon-Sun (6:00 AM - 9:30 PM)</p>
<p>PHONE:</p>
<p>(504) 891-2115</p>
<br>
<br>

<%= link_to 'Back to Doggy Daycare', pages_index_path, class: "btn btn-success" %>

app/views/pages/index.html.erb
<br>
<br>
<div class="jumbotron">
  <h1 class="display-3" style="text-align:center">DOGGY DAYCARE</h1>
  <p class="lead">Welcome to Doggy Daycare where we treat your dogs like our own.</p><p> We are excited to be of service for the entire New Orleans area.</p><p> At Dog Daycare, we strive to know every dog by name and treat</p><p> them like they are one of our own family members. </p>
</div>

<div class="container-fluid">
  <div class="row features">
    <div class="col-md-4">
      <img src="https://hd.unsplash.com/photo-1455757618770-0a58b0b28ebd" alt="dog in swing" class= "img responsive"> 
      <p> All the cutest dogs come to Doggy Daycare!! 
      </p>  
    </div>
    

    <div class="col-md-4">
        <img src="https://hd.unsplash.com/18/pups.JPG">
        <p>Look how happy these dauschunds are!!
        </p>
    </div>

    <div class="col-md-4">
        <img src="https://hd.unsplash.com/photo-1456087468887-17b7d7b076e0">
        <p> And this is how excited dogs are to be at Doggy Daycare!!
        </p>
    </div>

  </div>


<br>


<%= link_to 'About Doggy Daycare', pages_about_path, class: "btn btn-success" %>

app/views/vets/_form.html.erb
<%= simple_form_for(@vet) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :clinic %>
    <%= f.input :phone %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/vets/edit.html.erb
<h1>Editing Vet</h1>

<%= render 'form' %>

<%= link_to 'Show', @vet %> |
<%= link_to 'Back', vets_path %>

app/views/vets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vets</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Clinic</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vets.each do |vet| %>
      <tr>
        <td><%= vet.name %></td>
        <td><%= vet.clinic %></td>
        <td><%= vet.phone %></td>
        <td><%= link_to 'Show', vet %></td>
        <td><%= link_to 'Edit', edit_vet_path(vet) %></td>
        <td><%= link_to 'Destroy', vet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vet', new_vet_path %>

app/views/vets/new.html.erb
<h1>New Vet</h1>

<%= render 'form' %>

<%= link_to 'Back', vets_path %>

app/views/vets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vet.name %>
</p>

<p>
  <strong>Clinic:</strong>
  <%= @vet.clinic %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @vet.phone %>
</p>

<%= link_to 'Edit', edit_vet_path(@vet) %> |
<%= link_to 'Back', vets_path %>